name: Pull Request protector
description: Blocks 3rd-party pull requests based on user and files changed.
author: https://github.com/nickofthyme
requirements: []
configuration:
  properties:
    users:
      # https://github.com/gobwas/glob
      description: 'A list of allowed usernames. Does not support wildcards (i.e. "*").'
      type: array
      examples:
        - [nickofthyme, user-123]

    teams:
      # https://github.com/orgs/elastic/teams/datavis
      description: 'A list of allowed team slugs under the parent repo organization. Does not support wildcards (i.e. "*").'
      type: array
      examples:
        - [my-team-name]

    member:
      description: 'Allow members of repo organization (default: false). Requires org read access.'
      type: boolean
      default: true

    collaborator:
      description: 'Allow collaborators of repo organization (default: true).'
      type: boolean
      default: true

    files:
      description: 'A list of files or glob/minimatch patterns to block build for untrusted users.'
      type: array
      default: [.buildkite/**]
      examples:
        - [.buildkite/**, src/*]

    verified:
      description: 'If true, accepts only verified commits.'
      type: boolean
      default: true

    block_step:
      description: 'The block step used to block the pipeline.'
      $ref: "https://raw.githubusercontent.com/buildkite/pipeline-schema/master/schema.json#/definitions/blockStep"

    debug:
      description: 'Show verbose logging to aid in troubleshooting plugin config.'
      type: boolean
      default: false

    gh_token_env:
      description: 'Key of the environment variable containing the GitHub token.'
      type: string
      default: GITHUB_TOKEN

    gh_auth_env:
      description: 'Key of the environment variable containing the GitHub App auth json values.'
      type: string

  required: []
  additionalProperties: false
