name: Publish

on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'

      # TODO add tests

      - name: Build binary (linux/arm64)
        uses: skx/github-action-build@master
        with:
          builder: .github/build.sh
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          OS: linux
          ARCH: arm64

      - name: Build binary (linux/amd64)
        uses: skx/github-action-build@master
        with:
          builder: .github/build.sh
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          OS: linux
          ARCH: amd64

      - name: Upload the binaries
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: pull-request-protector-buildkite-plugin-*-*
